#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP2-1 -d brave
bspc monitor DP2-3 -d kitty leafpad

bspc config border_width         0
bspc config top_padding		35
bspc config window_gap          20
bspc config bottom_padding	5

bspc config split_ratio          0
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# dunst notifications daemon
dunst &

# polybar launch
bash ~/.config/polybar/launch.sh &

# display compositing
picom &

# for network connection and bluetooth
nm-applet &
blueman-applet &
